# Generated by Django 6.0.7 on 2026-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
